# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20160529_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/frames')),
            ],
        ),
        migrations.AlterModelOptions(
            name='artimage',
            options={'verbose_name_plural': 'Art Works'},
        ),
        migrations.AddField(
            model_name='product',
            name='homepage_list_icon',
            field=models.ImageField(default='', upload_to='media/homepage_list'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='slider_image',
            field=models.ImageField(default='', upload_to='media/slider'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artimage',
            name='frames',
            field=models.ManyToManyField(related_name='frames', to='gallery.Frame'),
        ),
    ]
