# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.CharField(default='info@artleafgallery.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='telephone',
            field=models.CharField(default='+123456', max_length=12),
            preserve_default=False,
        ),
    ]
