# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20160601_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Company'},
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.IntegerField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='telephone',
            field=models.CharField(max_length=13),
        ),
    ]
