# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20160606_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.IntegerField(max_length=2, unique=True),
        ),
    ]
