# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20160606_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='artimage',
            name='description',
            field=models.CharField(default='description', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artimage',
            name='dimension',
            field=models.CharField(default='30x30 In', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artimage',
            name='story',
            field=models.CharField(default='Story', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='order',
            field=models.IntegerField(unique=True),
        ),
    ]
