# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0011_auto_20160611_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='artimage',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
            preserve_default=False,
        ),
    ]
